### ISSUE TITLE
starter: breaks NodeJS 12 - npm 6.9.2 during install

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#2495]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When I try to install dependencies of Starter with NodeJS 12 and npm 6.9.2, I get the following error:

```bash
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-02-26T16_52_34_724Z-debug.log
```

The full log is:

```txt
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/username/.nvm/versions/node/v12.21.0/bin/node',
1 verbose cli   '/Users/username/.nvm/versions/node/v12.21.0/bin/npm',
1 verbose cli   'i'
1 verbose cli ]
2 info using npm@6.9.2
3 info using node@v12.21.0
4 verbose npm-session 2428965d1b0e5225
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall stark-starter@0.0.1
7 info lifecycle stark-starter@0.0.1~preinstall: stark-starter@0.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /Users/username/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
10 verbose stack     at FSReqCallback.oncomplete (fs.js:169:5)
11 verbose cwd /Users/username/dev/stark-nbb/starter
12 verbose Darwin 20.3.0
13 verbose argv "/Users/username/.nvm/versions/node/v12.21.0/bin/node" "/Users/username/.nvm/versions/node/v12.21.0/bin/npm" "i"
14 verbose node v12.21.0
15 verbose npm  v6.9.2
16 error cb.apply is not a function
17 verbose exit [ 1, true ]
```

After this try, the npm package is broken. I need to reset npm installation manually to fix it.
The error happens also on CI environment. 

## Expected behavior

The install of the starter should not break `npm` package.

## Minimal reproduction of the problem with instructions

1. Install NodeJS 12
2. Install npm@6.9.2
3. Remove node_modules/ and package-lock.json in starter folder
4. Execute `npm install` in starter folder

## What is the motivation / use case for changing the behavior?

Fixing bugs.

I tried locally to use npm@6.10.3 with NodeJS 12 and the install is going well in starter folder.

## Environment

<pre><code>
Angular version: 7.x
Stark version: 10.1.0

 
For Tooling issues:
- Node version: 12.21.0 & npm 6.9.2
- Platform: Mac & Linux

Others:

</code></pre>

**Comment by SuperITMan** [comment]
Closed by #2659
