### ISSUE TITLE
Review webdriver install

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#35]
Make sure webdriver config is ok (cfr what we did internally before for it with custom script, etc)

**Comment by christophercr** [comment]
With the current version of webdriver there is an issue while downloading the manager:

```
stark-starter@0.0.1 webdriver:update /home/travis/build/christophercr/stark/starter
> node ./node_modules/protractor/bin/webdriver-manager update

[15:55:55] I/file_manager - creating folder /home/travis/build/christophercr/stark/starter/node_modules/protractor/node_modules/webdriver-manager/selenium
(node:5269) UnhandledPromiseRejectionWarning: Error: Failed to make Github request, rate limit reached.
    at Request.req.on.response (/home/travis/build/christophercr/stark/starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/binaries/config_source.js:155:28)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/travis/build/christophercr/stark/starter/node_modules/request/request.js:1062:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```
