### ISSUE TITLE
build: showcase - "RangeError: Maximum call stack size exceeded" due to Angular build-optimizer on prettier/parser-typescript.js

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#566]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Angular build-optimizer throws an error while building the production build with webpack:
```
ERROR in ./node_modules/prettier/parser-typescript.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
RangeError: Maximum call stack size exceeded
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56952:28)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57078:46)
    at visitor (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/home/travis/build/NationalBankBelgium/stark/showcase/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
 @ ./node_modules/@nationalbankbelgium/stark-ui/fesm5/stark-ui.js 410:4-41
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
```

## Expected behavior

No errors while generating the webpack production build.

## Minimal reproduction of the problem with instructions

Run `npm run build:aot:prod` command in the showcase on Node 6.

## What is the motivation / use case for changing the behavior?

Stable build process.

## Environment

<pre><code>
Angular version: 6.0.9
 
For Tooling issues:
- Node version: 6.X
- Platform:  ALL

**Comment by christophercr** [comment]
Closed by #576
